### ISSUE TITLE
Question: providing a network interface fails for me on MacOS and Linux

### ISSUE THREAD

**Issue by sassman** [hermitcore/rusty-hermit#113]
This is a very awesome project, just recently discovered it. Now I'm preparing a little talk at the Rust Munich Meetup for which I prepare a little [demo](https://github.com/sassman/rust-kx-II/tree/main/echo-hermit).

Nothing fancy, just an echo TCP Server. So far so good, I got the other example (hello world) working.

But for this one I'm not getting the network interface right. I tried `qemu` and `uhyve` but no luck so far.

- `qemu-system-x86_64 -netdev socket,id=mynet0,connect=:8080 ....` did not work
- `qemu-system-x86_64 -netdev user,id=mynet0,net=192.168.76.0/24,dhcpstart=192.168.76.9 ...` did not work
- `HERMIT_IP="192.168.76.9" HERMIT_GATEWAY="192.168.76.254" HERMIT_MASK="255.255.255.0" HERMIT_NETIF=mynet0 cargo run --release` for the network above as described for `uhyve`

The error I'm getting:
```plain
...
[0][INFO] Compiled with ACPI support
[0][INFO] Compiled with SMP support
[0][INFO] HermitCore is running on common system!
[INFO] Spawn network thread with id 2
[WARN] Ethernet interface not available
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "accept failed" }', src/main.rs:9:47
[0][INFO] Number of interrupts
[0][INFO] [0][7]: 3
[0][INFO] Shutting down system
```

I'm not sure what am I missing. Maybe you could give me a hint how the network interface can be provided.

Many thanks in Advance

**Comment by jschwe** [comment]
Did you setup a tap device on the host system as described in https://github.com/hermitcore/rusty-hermit#network-support?

**Comment by sassman** [comment]
Thanks for the feedback. I got it working now!! Very cool.

There were 2 issues:
- I was missing the `-device virtio-net-pci,netdev=net0,disable-legacy=on` option
- `-m 64M` seems not enough memory, only at `-m 512M` it starts to work for me

In cases of `< 512M` it shows this error:

```plain
[0][INFO] HermitCore is running on common system!
[0][INFO] Found virtio network device with device id 0x1041
[0][WARN] Currently only mapping of 64 bit BAR's is supported!
[0][INFO] Non Virtio PCI capability with id 11 found. And NOT used.
[0][ERROR] Found virtio capability whose BAR is not mapped or non existing. Capability of type 5 and id 0 for device 1041, can not be used!
[0][INFO] Feature set wanted by network driver are in conformance with specification.
[0][INFO] Feature set wanted by network driver are in conformance with specification.
[0][INFO] Driver found a subset of features for virtio device 1041. Features are: [VIRTIO_NET_F_MAC, VIRTIO_NET_F_STATUS, VIRTIO_F_RING_INDIRECT_DESC, VIRTIO_F_VERSION_1]
[0][INFO] Features have been negotiated between virtio network device 1041 and driver.
[0][INFO] Created SplitVq: idx=0, size=256
[0][INFO] Created SplitVq: idx=1, size=256
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ()', src/mm/mod.rs:235:66
[0][INFO] Number of interrupts
[0][INFO] [0][7]: 1
[0][INFO] Shutting down system
```

Do you have any insights why the networking stack increases the footprint soo much?

**Comment by stlankes** [comment]
Naive questions. Does Qemu supports virtio on macOS?

Could you test, if the emulation of a RTL8139 network interface works on your system? The following command should start a VM with a emulation of this interface:

> qemu-system-x86_64 -smp 1 -m 256M -kernel lpath_to_loader/rusty-loader -initrd path_to_hhtpd/httpd -display none -serial stdio -netdev user,id=u1,hostfwd=tcp::9975-:9975 -device rtl8139,netdev=u1 -cpu qemu64,apic,fsgsbase,rdtscp,xsave,fxsr,rdrand

**Comment by sassman** [comment]
@stlankes awesome! 

The `dhcpv4` feature together with the `rtl8139` chip and the port forwarding works on macOS and on Linux. Also it works with the memory kept low at `64M`.

```toml
# .cargo/config

runner = "qemu-system-x86_64 -device rtl8139,netdev=net0 -netdev user,id=net0,hostfwd=tcp::8080-:8080 -cpu qemu64,apic,fsgsbase,rdtscp,xsave,fxsr -display none -smp 1 -m 64M -serial stdio -kernel ../rusty-loader/target/x86_64-unknown-hermit-loader/release/rusty-loader -initrd"

```

full example [is here](https://github.com/sassman/rust-kx-II/commit/64bc7e1d2aee7468fec439b57b4ecaaed9221e81)

**Comment by sassman** [comment]
Thanks a lot guys and keep up this nice efforts, awesome project.
